/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Usuario;

/**
 *
 * @author Harold Díaz
 * Karl Weierstrass — 'When I wrote this, only God and I understood what I was doing. Now, God only knows.'
 */
public class Bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenido
     */
    static Usuario usuario;
    
    public Bienvenido() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonGuia = new javax.swing.JButton();
        botonVisitante = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TrueCity");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Bienvenido a TrueCity");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("de ser guías y explorar su lugar de origen");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 130, 230, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("conozcan mejor la ciudad que visitan,");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 90, 230, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("a la vez que les permite vivir la experiencia");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 110, 230, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Esta aplicación busca que los turistas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 70, 230, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Elige qué te gustaría ser hoy");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 210, 17);

        botonGuia.setBackground(new java.awt.Color(255, 102, 0));
        botonGuia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonGuia.setForeground(new java.awt.Color(255, 255, 255));
        botonGuia.setText("Guía");
        botonGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuiaActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuia);
        botonGuia.setBounds(60, 220, 100, 30);

        botonVisitante.setBackground(new java.awt.Color(255, 102, 0));
        botonVisitante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonVisitante.setForeground(new java.awt.Color(255, 255, 255));
        botonVisitante.setText("Visitante");
        botonVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVisitanteActionPerformed(evt);
            }
        });
        getContentPane().add(botonVisitante);
        botonVisitante.setBounds(240, 220, 100, 30);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/img/logo.jpeg"))); // NOI18N
        getContentPane().add(labelLogo);
        labelLogo.setBounds(20, 20, 120, 120);

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/img/miniFondo.jpeg"))); // NOI18N
        getContentPane().add(labelFondo);
        labelFondo.setBounds(0, -10, 440, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuiaActionPerformed
        // TODO add your handling code here:
        VentanaGuia a = new VentanaGuia ();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGuiaActionPerformed

    private void botonVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVisitanteActionPerformed
        // TODO add your handling code here:
        VentanaVisitante a = new VentanaVisitante ();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVisitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuia;
    private javax.swing.JButton botonVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables
}
